# Generated by Django 3.1.7 on 2021-04-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210414_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedb',
            name='gender',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
