# Generated by Django 3.1.7 on 2021-04-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phonedb_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tel_no',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
